import os

import pytest

from cppast2autopxd import generate_pxd

HERE = os.path.dirname(os.path.abspath(__file__))
HEADERS = os.path.join(HERE, "headers")
MINI_PCL = os.path.join(HEADERS, "mini_pcl")


def test_rectangle():
    result = generate_pxd(
        os.path.join(HEADERS, "rectangle.hpp"),
        extern_from="rectangle.hpp",
    )
    text = result.text
    assert 'cdef extern from "rectangle.hpp" namespace "shapes" nogil:' in text
    assert "cdef cppclass Rectangle:" in text
    assert "Rectangle(int x0, int y0, int x1, int y1) except +" in text
    assert "int getArea() except +" in text
    assert "void move(int dx, int dy) except +" in text
    # public data members survive
    assert "int x0" in text


def test_point_types_flattens_anonymous_unions():
    result = generate_pxd(
        os.path.join(MINI_PCL, "pcl", "point_types.h"),
        extern_from="pcl/point_types.h",
        namespaces=["pcl"],
    )
    text = result.text
    assert 'cdef extern from "pcl/point_types.h" namespace "pcl" nogil:' in text
    # plain data structs come out as cdef struct
    assert "cdef struct PointXYZ:" in text
    for member in ("float x", "float y", "float z", "float data[4]"):
        assert member in text
    # nested unions in PointXYZRGB flatten all the way down
    assert "uint8_t r" in text
    assert "float rgb" in text
    assert "uint32_t rgba" in text
    assert "from libc.stdint cimport" in text


def test_point_cloud_template():
    result = generate_pxd(
        os.path.join(MINI_PCL, "pcl", "point_cloud.h"),
        extern_from="pcl/point_cloud.h",
        namespaces=["pcl"],
    )
    text = result.text
    assert "cdef cppclass PointCloud[PointT]:" in text
    assert "ctypedef shared_ptr[PointCloud[PointT]] Ptr" in text
    assert "vector[PointT] points" in text
    assert "size_t size() except +" in text
    assert "PointT& operator[](size_t n) except +" in text
    assert "PointCloud(unsigned int width_, unsigned int height_) except +" in text
    assert "from libcpp.memory cimport shared_ptr" in text
    assert "from libcpp.vector cimport vector" in text


def test_features_full_matrix():
    result = generate_pxd(
        os.path.join(HEADERS, "features.hpp"),
        extern_from="features.hpp",
        namespaces=["demo"],
    )
    text = result.text
    # enums
    assert "cdef enum Color:" in text
    assert "cdef enum class Mode:" in text
    assert "RED" in text and "Fast" in text
    # typedef and using alias
    assert "ctypedef unsigned int index_t" in text
    assert "ctypedef map[string, int] name_map" in text
    # class surface
    assert "cdef cppclass Widget:" in text
    assert "Widget(int id) except +" in text
    assert "Widget(const Widget& other) except +" in text  # copy ctor kept
    assert text.count("Widget(Widget&&") == 0  # move ctor dropped
    assert "int id() except +" in text
    assert "@staticmethod" in text
    # default arguments expand into overloads (no `=*` for extern functions)
    assert "Widget make() except +" in text
    assert "Widget make(int id) except +" in text
    assert "double& operator[](size_t idx) except +" in text
    assert "bool operator==(const Widget& other) except +" in text
    # private members skipped
    assert "secret_" not in text
    assert "hidden" not in text
    # free functions: default args expand into overloads
    assert "vector[string] split(const string& text) except +" in text
    assert "vector[string] split(const string& text, char sep) except +" in text
    assert "int add(int a, int b) except +" in text


def test_const_kept_without_except_plus():
    result = generate_pxd(
        os.path.join(HEADERS, "features.hpp"),
        extern_from="features.hpp",
        namespaces=["demo"],
        except_plus=False,
    )
    text = result.text
    assert "int id() const" in text
    assert "except +" not in text


def test_banner_and_distutils_header():
    result = generate_pxd(os.path.join(HEADERS, "rectangle.hpp"))
    assert result.text.startswith("# Auto-generated by cppast2autopxd")
    assert "# distutils: language = c++" in result.text


def test_missing_header_raises():
    from cppast2autopxd.parser import ParseError

    with pytest.raises(ParseError):
        generate_pxd(os.path.join(HEADERS, "no_such_file.hpp"))
