"""High-level generation API: header(s) in, pxd file(s) out."""

from __future__ import annotations

import os
import re
from typing import List, Optional

from . import __version__
from .config import GeneratorConfig, HeaderJob
from .emitter import EmitOptions, emit_module
from .parser import ParseOptions, parse_header
from .typemap import TypeMapper


def generate_pxd(
    header: str,
    *,
    extern_from: Optional[str] = None,
    include_dirs: Optional[List[str]] = None,
    defines: Optional[List[str]] = None,
    std: Optional[str] = None,
    language: str = "c++",
    macros: bool = True,
    extra_args: Optional[List[str]] = None,
    namespaces: Optional[List[str]] = None,
    include_names: Optional[List[str]] = None,
    exclude_names: Optional[List[str]] = None,
    substitutions=None,
    extra_cimports: Optional[List[str]] = None,
    nogil: bool = True,
    except_plus: Optional[bool] = None,
    banner: Optional[str] = None,
    compile_db: Optional[str] = None,
) -> "GenerationResult":
    """Generate pxd text for one header. Returns text plus warnings.

    ``except_plus`` defaults to True for C++ and False for C (`except +`
    requires C++ compilation).

    ``compile_db`` points at a CMake ``compile_commands.json`` (or the
    build directory containing it); include dirs, defines, the language
    standard, and sysroot flags are then taken from the best-matching
    database entry — explicitly passed values are kept and take
    precedence, the database appends.

    ``std=None`` means: the database's ``-std=`` if one applies,
    otherwise ``c++14``. Passing a standard explicitly always wins.
    """
    if except_plus is None:
        except_plus = language != "c"

    db_warnings: List[str] = []
    if compile_db:
        from .compiledb import flags_for, load_compile_db

        db_flags = flags_for(header, load_compile_db(compile_db))
        include_dirs = list(include_dirs or []) + db_flags.include_dirs
        defines = list(defines or []) + db_flags.defines
        extra_args = list(extra_args or []) + db_flags.extra_args
        db_warnings = list(db_flags.warnings)
        if std is None:
            std = db_flags.std
    if std is None:
        std = "c++14"

    mapper = TypeMapper(substitutions=dict(substitutions or {}))
    # Names brought in by user-supplied cimport lines are declarable.
    for line in extra_cimports or []:
        mapper.known_names.update(_imported_names(line))
    options = ParseOptions(
        include_dirs=list(include_dirs or []),
        defines=list(defines or []),
        std=std,
        language=language,
        macros=macros,
        extra_args=list(extra_args or []),
        namespaces=list(namespaces or []),
        include_names=list(include_names or []),
        exclude_names=list(exclude_names or []),
        extern_from=extern_from,
    )
    module = parse_header(header, options, mapper)
    if banner is None:
        banner = (
            f"Auto-generated by cppast2autopxd {__version__} "
            f"from {os.path.basename(header)}.\n"
            "Do not edit by hand; re-run the generator instead."
        )
    text = emit_module(
        module,
        mapper.cimports,
        EmitOptions(
            nogil=nogil,
            except_plus=except_plus,
            cplus=language != "c",
            extra_cimports=list(extra_cimports or []),
            banner=banner,
        ),
    )
    return GenerationResult(
        text=text, warnings=db_warnings + list(module.warnings),
        module=module,
    )


class GenerationResult:
    def __init__(self, text: str, warnings: List[str], module=None):
        self.text = text
        self.warnings = warnings
        # The lowered IR (ir.Module) — consumed by the pyx scaffolder.
        self.module = module


def _imported_names(cimport_line: str) -> List[str]:
    """Extract the names a cimport line brings into scope."""
    names: List[str] = []
    m = re.match(r"\s*from\s+\S+\s+cimport\s+(.+)", cimport_line)
    if m:
        for part in m.group(1).split(","):
            part = part.strip()
            if " as " in part:
                part = part.split(" as ")[-1].strip()
            if part and part != "*":
                names.append(part)
        return names
    m = re.match(r"\s*cimport\s+(.+)", cimport_line)
    if m:
        for part in m.group(1).split(","):
            part = part.strip()
            if " as " in part:
                part = part.split(" as ")[-1].strip()
            else:
                part = part.split(".")[0]
            if part:
                names.append(part)
    return names


def derive_pxd_module(output: str) -> str:
    """Dotted cimport path of a generated pxd, from its file location.

    Walks up from the output file while ``__init__.pxd``/``__init__.py``
    mark package directories, so ``src/pcl/pxd/point_types.pxd`` becomes
    ``pcl.pxd.point_types``. Inside a package layout the bare basename
    would cimport the wrong module (or nothing at all).
    """
    parts = [os.path.splitext(os.path.basename(output))[0]]
    d = os.path.dirname(os.path.abspath(output))
    while any(
        os.path.exists(os.path.join(d, init))
        for init in ("__init__.pxd", "__init__.py")
    ):
        parts.insert(0, os.path.basename(d))
        parent = os.path.dirname(d)
        if parent == d:
            break
        d = parent
    return ".".join(parts)


def scaffold_collides(pyx_path: str, pxd_path: str) -> bool:
    """True when the scaffold would form the SAME Cython module as the pxd.

    A ``foo.pyx`` next to ``foo.pxd`` makes Cython treat the pxd as the
    pyx's own declaration file — ``cimport``-ing it from itself then
    fails. The scaffold must live under a different module name.
    """
    a = os.path.splitext(os.path.abspath(pyx_path))[0]
    b = os.path.splitext(os.path.abspath(pxd_path))[0]
    return a == b


def run_config(cfg: GeneratorConfig, verbose: bool = True) -> List[str]:
    """Run every header job in a config. Returns all warnings."""
    all_warnings: List[str] = []
    for job in cfg.headers:
        result = generate_job(cfg, job)
        os.makedirs(os.path.dirname(job.output) or ".", exist_ok=True)
        with open(job.output, "w", encoding="utf-8") as fh:
            fh.write(result.text)
        if verbose:
            rel = os.path.relpath(job.output, cfg.base_dir)
            print(f"[cppast2autopxd] wrote {rel}")
            for w in result.warnings:
                print(f"[cppast2autopxd]   warning: {w}")
        all_warnings.extend(result.warnings)

        if job.pyx_scaffold:
            if scaffold_collides(job.pyx_scaffold, job.output):
                raise ValueError(
                    f"pyx_scaffold {job.pyx_scaffold!r} and output "
                    f"{job.output!r} would form the same Cython module; "
                    "give the scaffold a different name (e.g. _wrap.pyx)"
                )
            if os.path.exists(job.pyx_scaffold):
                if verbose:
                    print(
                        "[cppast2autopxd] scaffold exists, left untouched: "
                        + os.path.relpath(job.pyx_scaffold, cfg.base_dir)
                    )
            else:
                from .pyx_scaffold import render_scaffold

                pxd_module = job.pxd_module or derive_pxd_module(job.output)
                text = render_scaffold(
                    result.module,
                    pxd_module,
                    job.extern_from or os.path.basename(job.path),
                )
                os.makedirs(
                    os.path.dirname(job.pyx_scaffold) or ".", exist_ok=True
                )
                with open(job.pyx_scaffold, "w", encoding="utf-8") as fh:
                    fh.write(text)
                if verbose:
                    print(
                        "[cppast2autopxd] scaffolded "
                        + os.path.relpath(job.pyx_scaffold, cfg.base_dir)
                    )
    return all_warnings


def generate_job(cfg: GeneratorConfig, job: HeaderJob) -> GenerationResult:
    return generate_pxd(
        job.path,
        extern_from=job.extern_from,
        include_dirs=cfg.include_dirs,
        defines=cfg.defines,
        std=cfg.std,
        language=job.language or cfg.language,
        macros=cfg.macros,
        extra_args=cfg.extra_args,
        namespaces=job.namespaces,
        include_names=job.include_names,
        exclude_names=job.exclude_names,
        substitutions=cfg.substitutions,
        extra_cimports=job.extra_cimports,
        nogil=cfg.nogil,
        except_plus=cfg.except_plus,
        compile_db=cfg.compile_db,
    )
