#!/usr/bin/env bash
# scaffold_pkg.sh - generate a buildable Cython/Python package skeleton from a
# C/C++ header, using cppast_autopxd for the .pxd. This is the lightweight,
# dependency-free alternative to a cookiecutter template (no network, no
# interactive prompts, fully reproducible).
#
# Usage:
#   ./scaffold_pkg.sh --name <pkg> --header path/to/foo.h [--source path/to/foo.cpp]
#                     [--namespace ns] [--out DIR] [--std c++14]
#
# Produces under <out>/<pkg>/:
#   src/<header>            (+ src/<source> if given)
#   <header_stem>.pxd       (generated by cppast_autopxd)
#   <pkg>.pyx               (starter wrapper that cimports the .pxd)
#   pyproject.toml, setup.py, build_and_test.sh, README.md
#
# Then:  cd <out>/<pkg> && ./build_and_test.sh
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOL="$REPO/cppast_autopxd"

NAME="" HEADER="" SOURCE="" NS="" OUT="generated" STD="c++14"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --name) NAME="$2"; shift 2;;
    --header) HEADER="$2"; shift 2;;
    --source) SOURCE="$2"; shift 2;;
    --namespace) NS="$2"; shift 2;;
    --out) OUT="$2"; shift 2;;
    --std) STD="$2"; shift 2;;
    -h|--help) sed -n '2,20p' "$0"; exit 0;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done

[[ -n "$NAME" && -n "$HEADER" ]] || { echo "error: --name and --header are required" >&2; exit 2; }
[[ -f "$HEADER" ]] || { echo "error: header not found: $HEADER" >&2; exit 2; }
[[ -x "$TOOL" ]] || { echo "error: build the tool first: (cd $REPO && ./bootstrap.sh)" >&2; exit 1; }

PKGDIR="$OUT/$NAME"
hdr_base="$(basename "$HEADER")"
hdr_stem="${hdr_base%.*}"
mkdir -p "$PKGDIR/src"
cp "$HEADER" "$PKGDIR/src/$hdr_base"
src_line=""
if [[ -n "$SOURCE" ]]; then
  [[ -f "$SOURCE" ]] || { echo "error: source not found: $SOURCE" >&2; exit 2; }
  cp "$SOURCE" "$PKGDIR/src/$(basename "$SOURCE")"
  src_line="\"src/$(basename "$SOURCE")\", "
fi

# 1) generate the .pxd
"$TOOL" --output_dir "$PKGDIR" --xml_dir "" --std "$STD" "$PKGDIR/src/$hdr_base"
echo "generated: $PKGDIR/$hdr_stem.pxd"

# 2) starter .pyx (cimports the generated declarations)
cat > "$PKGDIR/$NAME.pyx" <<PYX
# $NAME.pyx - hand-written Cython wrapper. The .pxd it cimports is generated by
# cppast_autopxd; edit this file to expose the C++ API you want in Python.
# distutils: language = c++
${src_line:+# distutils: sources = src/$(basename "${SOURCE:-}")}
cimport $hdr_stem  # generated declarations ($hdr_stem.pxd)

# TODO: add Python-callable wrappers, e.g.:
#   def my_func(int a, int b):
#       return $hdr_stem.my_func(a, b)
PYX

# 3) build files
cat > "$PKGDIR/pyproject.toml" <<TOML
[build-system]
requires = ["setuptools>=61", "wheel", "Cython>=3.0"]
build-backend = "setuptools.build_meta"

[project]
name = "$NAME"
version = "0.0.1"
description = "Generated by cppast_autopxd scaffold from $hdr_base"
requires-python = ">=3.9"
TOML

cat > "$PKGDIR/setup.py" <<PY
import sys
from setuptools import setup, Extension
from Cython.Build import cythonize

# Portable C++ standard flag: MSVC uses /std:, others -std=. On Windows the same
# build emits a .pyd; on macOS/Linux a .so — both are the compiled extension.
cxx_std = ["/std:$STD"] if sys.platform == "win32" else ["-std=$STD"]

extensions = [
    Extension(
        name="$NAME",
        sources=["$NAME.pyx", ${src_line%, }],
        include_dirs=["src", "."],
        language="c++",
        extra_compile_args=cxx_std,
    )
]
setup(
    packages=[],
    py_modules=[],
    ext_modules=cythonize(extensions, language_level="3"),
)
PY

cat > "$PKGDIR/build_and_test.sh" <<'SH'
#!/usr/bin/env bash
# Build the extension in place and import it. Set PY=/path/to/python to choose
# an interpreter (defaults to python3). On macOS, exports SDKROOT for clang.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PY="${PY:-python3}"
[[ "$(uname)" == "Darwin" ]] && export SDKROOT="${SDKROOT:-$(xcrun --show-sdk-path)}"
cd "$HERE"
"$PY" setup.py build_ext --inplace
"$PY" -c "import __PKG__ as m; print('imported __PKG__ OK ->', [n for n in dir(m) if not n.startswith('__')])"
SH
sed -i.bak "s/__PKG__/$NAME/g" "$PKGDIR/build_and_test.sh" && rm -f "$PKGDIR/build_and_test.sh.bak"
chmod +x "$PKGDIR/build_and_test.sh"

cat > "$PKGDIR/README.md" <<MD
# $NAME

Auto-scaffolded by \`cppast_autopxd\` from \`$hdr_base\`.

- \`$hdr_stem.pxd\` — generated C++ declarations (regenerate with the tool).
- \`$NAME.pyx\` — hand-written wrapper (edit this).
- Build & smoke-test: \`./build_and_test.sh\`  (or \`pip install .\`)
MD

echo
echo "scaffold ready: $PKGDIR"
echo "next: edit $PKGDIR/$NAME.pyx, then (cd $PKGDIR && ./build_and_test.sh)"
