# mathlib_py.pyx - Cython wrapper exposing the C++ mathlib API (declared in the
# generated mathlib.pxd) to Python. This is the hand-written glue: the .pxd is
# auto-generated by cppast_autopxd; only this thin wrapper is written by hand.
# distutils: language = c++
# distutils: sources = src/mathlib.cpp

cimport mathlib  # the generated declarations (mathlib.pxd)


def add(int a, int b) -> int:
    """Wraps mathlib::add."""
    return mathlib.add(a, b)


def hypot2(double x, double y) -> float:
    """Wraps mathlib::hypot2."""
    return mathlib.hypot2(x, y)


cdef class Accumulator:
    """Wraps the C++ mathlib::Accumulator value type."""
    cdef mathlib.Accumulator _c   # held by value

    def __cinit__(self, initial=None):
        if initial is None:
            self._c = mathlib.Accumulator()
        else:
            self._c = mathlib.Accumulator(<double>initial)

    def add(self, double v):
        self._c.add(v)

    def total(self) -> float:
        return self._c.total()

    def count(self) -> int:
        return self._c.count()
