"""setup.py - build the mathlib_py extension from the Cython wrapper + C++ impl.

Project metadata lives in pyproject.toml; this file only declares the C++/Cython
extension (setuptools has no declarative form for cythonize()). The .pxd that
mathlib_py.pyx cimports is auto-generated by cppast_autopxd (see gen.sh).

Build:  python -m pip install .            (PEP 517, isolated)
   or:  python setup.py build_ext --inplace
"""
import sys
from setuptools import setup, Extension
from Cython.Build import cythonize

# Portable C++ standard flag: MSVC (Windows) uses /std:, everything else -std=.
# On Windows the very same build produces a .pyd instead of a .so.
cxx_std = ["/std:c++14"] if sys.platform == "win32" else ["-std=c++14"]

extensions = [
    Extension(
        name="mathlib_py",
        sources=["mathlib_py.pyx", "src/mathlib.cpp"],
        include_dirs=["src", "."],   # src/ for mathlib.h, . for mathlib.pxd
        language="c++",
        extra_compile_args=cxx_std,
    )
]

setup(
    # Top-level extension only — no Python packages (keeps the built .so at the
    # project root instead of setuptools auto-discovering src/).
    packages=[],
    py_modules=[],
    ext_modules=cythonize(extensions, language_level="3"),
)
