# miniz_py.pyx - Cython wrapper exposing miniz's compression API to Python.
# The cimported declarations (miniz.pxd) are auto-generated by cppast_autopxd
# from the real, unmodified miniz 3.0.2 header. Only this thin wrapper is
# hand-written.
# distutils: language = c++
# distutils: sources = src/miniz.c

from libc.stdlib cimport malloc, free
cimport miniz


def crc32(bytes data, unsigned long seed=0) -> int:
    """CRC-32 of `data` (miniz mz_crc32), matching zlib's crc32."""
    cdef const unsigned char* p = <const unsigned char*>data
    return miniz.mz_crc32(seed, p, len(data))


def adler32(bytes data, unsigned long seed=1) -> int:
    """Adler-32 of `data` (miniz mz_adler32)."""
    cdef const unsigned char* p = <const unsigned char*>data
    return miniz.mz_adler32(seed, p, len(data))


def version() -> str:
    """miniz version string (mz_version)."""
    return miniz.mz_version().decode("ascii")


def compress(bytes data, int level=6) -> bytes:
    """zlib-compress `data` using miniz mz_compress2. Returns the compressed bytes."""
    cdef miniz.mz_ulong src_len = len(data)
    cdef miniz.mz_ulong dst_len = miniz.mz_compressBound(src_len)
    cdef unsigned char* dst = <unsigned char*>malloc(dst_len)
    if dst == NULL:
        raise MemoryError()
    cdef const unsigned char* src = <const unsigned char*>data
    cdef int status
    try:
        status = miniz.mz_compress2(dst, &dst_len, src, src_len, level)
        if status != 0:
            raise RuntimeError("mz_compress2 failed: status=%d" % status)
        return (<char*>dst)[:dst_len]
    finally:
        free(dst)


def uncompress(bytes data, Py_ssize_t expected_size) -> bytes:
    """Inflate `data` (miniz mz_uncompress) into a buffer of `expected_size`."""
    cdef miniz.mz_ulong dst_len = expected_size
    cdef unsigned char* dst = <unsigned char*>malloc(dst_len if dst_len > 0 else 1)
    if dst == NULL:
        raise MemoryError()
    cdef const unsigned char* src = <const unsigned char*>data
    cdef int status
    try:
        status = miniz.mz_uncompress(dst, &dst_len, src, len(data))
        if status != 0:
            raise RuntimeError("mz_uncompress failed: status=%d" % status)
        return (<char*>dst)[:dst_len]
    finally:
        free(dst)
